version: "3.8"

services:
  frontend:
    container_name: react-frontend
    image: sega1294/react-frontend:latest@sha256:91f2f62879617fcb44e12edb75a03609615f6dee648969eeb9290114766614dd
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    restart: always
  backend:
    container_name: flask-backend
    image: sega1294/flask-backend:latest@sha256:3bd7b98d29f5fb62f7e5a7c8e6f94833b2feaffeef97a70c7b3ca54e66080224
    volumes:
      - /usr/share/caster/log/:/code/caster/log/
    ports:
      - 5000:5000
    restart: always
  caster:
    container_name: caster-server
    image: sega1294/caster-server:latest@sha256:b322fa42269823e7bfc2decb61d21ba7555ef15ce1065222354a413a18a9a3b0
    ports:
      - 2101:2101
    devices:
      - "/dev/ttyACM0"
    restart: always
